"""initial

Revision ID: d596d3d1a363
Revises: 
Create Date: 2026-04-05 13:03:52.995615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd596d3d1a363'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_id', sa.String(length=16), nullable=True),
    sa.Column('product_id', sa.String(length=16), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_table('kiosk_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('ai_response_text', sa.Text(), nullable=True),
    sa.Column('ai_provider_used', sa.String(length=64), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.Column('payment_provider', sa.String(length=64), nullable=True),
    sa.Column('payment_amount', sa.INTEGER(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kiosk_sessions_created_at', 'kiosk_sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_kiosk_sessions_not_cleared', 'kiosk_sessions', ['id'], unique=False, postgresql_where=sa.text('cleared_at IS NULL'))
    op.create_index('idx_kiosk_sessions_payment_status', 'kiosk_sessions', ['payment_status'], unique=False, postgresql_where=sa.text('payment_status IS NOT NULL'))
    op.create_index('idx_kiosk_sessions_state', 'kiosk_sessions', ['state'], unique=False)
    op.create_index(op.f('ix_kiosk_sessions_state'), 'kiosk_sessions', ['state'], unique=False)
    op.create_table('operator_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_operator_configs_category'), 'operator_configs', ['category'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['kiosk_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_events_session_id', 'analytics_events', ['session_id'], unique=False)
    op.create_index('idx_analytics_events_timestamp', 'analytics_events', ['timestamp'], unique=False)
    op.create_index('idx_analytics_events_type', 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_table('print_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['kiosk_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_jobs_session_id'), 'print_jobs', ['session_id'], unique=True)
    op.create_index(op.f('ix_print_jobs_status'), 'print_jobs', ['status'], unique=False)
    # Drop legacy tables if they exist (from pre-Alembic schema)
    op.execute('DROP TABLE IF EXISTS jobs CASCADE')
    op.execute('DROP TABLE IF EXISTS schema_migrations CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dirty', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text])", name=op.f('jobs_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('idx_jobs_task_type'), 'jobs', ['task_type'], unique=False)
    op.create_index(op.f('idx_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('idx_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_print_jobs_status'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_session_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index('idx_analytics_events_type', table_name='analytics_events')
    op.drop_index('idx_analytics_events_timestamp', table_name='analytics_events')
    op.drop_index('idx_analytics_events_session_id', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_operator_configs_category'), table_name='operator_configs')
    op.drop_table('operator_configs')
    op.drop_index(op.f('ix_kiosk_sessions_state'), table_name='kiosk_sessions')
    op.drop_index('idx_kiosk_sessions_state', table_name='kiosk_sessions')
    op.drop_index('idx_kiosk_sessions_payment_status', table_name='kiosk_sessions', postgresql_where=sa.text('payment_status IS NOT NULL'))
    op.drop_index('idx_kiosk_sessions_not_cleared', table_name='kiosk_sessions', postgresql_where=sa.text('cleared_at IS NULL'))
    op.drop_index('idx_kiosk_sessions_created_at', table_name='kiosk_sessions')
    op.drop_table('kiosk_sessions')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
